In [1]:
import os
import sys
import pandas as pd
import numpy as np
import pkgutil
sys.version

'3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]'

In [2]:
from opentrons import labware
from opentrons import robot

C:\Users\Brian\.opentrons\deck_calibration.json not found. Loading defaults
C:\Users\Brian\.opentrons\robot_settings.json not found. Loading defaults
C:\Users\Brian\.opentrons\deck_calibration.json not found. Loading defaults
C:\Users\Brian\.opentrons\robot_settings.json not found. Loading defaults
C:\Users\Brian\.opentrons\deck_calibration.json not found. Loading defaults
C:\Users\Brian\.opentrons\robot_settings.json not found. Loading defaults

In [3]:
# import opentrons
# package = opentrons
# for importer, modname, ispkg in pkgutil.iter_modules(package.__path__):
#     print("Found submodule %s (is a package: %s)" % (modname, ispkg))

In [ ]:
#Parameters
dmso_loc = 'A1' #location of DMSO; assumed to be 2ml tube
drug1_loc = 'A'
drug2_loc = 'B'
drug3_loc = 'C'

dmso_vol1 = 10 #if dealing with spreadsheet, change this
dmso_vol2 = 10 #for drug 2 (rows 1-6)
dmso_vol3 = 10 #for drug 3 (rows 6-12)
drug_vol1 = 10
drug_vol2 = 10
drug_vol3 = 10

used_cols = [ #comment out unused
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
#     'G',
#     'H',
]
used_rows2 = list(range(1:7)) #remember last # is exclusive. 1st drug in this series
used_rows3 = list(range(1:7))

drug_stock_loc = { #exact well where the drug stock solution for a specific row/col is located
    'A':
    'B':
    'C':
    'D':
    'E':
    'F':
    1:
    2:
    3:
    4:
    5:
    6:
    7:
    8:
    9:
    10:
    11:
    12:
}

input_file = 'numbers1.csv'

In [ ]:
#init, make sure it works
robot.connect()
robot.home

In [9]:
labware.list()

['12-well-plate',
 '24-vial-rack',
 '24-well-plate',
 '384-plate',
 '48-vial-plate',
 '48-well-plate',
 '5ml-3x4',
 '6-well-plate',
 '96-PCR-flat',
 '96-PCR-tall',
 '96-deep-well',
 '96-flat',
 '96-well-plate-20mm',
 'MALDI-plate',
 'PCR-strip-tall',
 'T25-flask',
 'T75-flask',
 'alum-block-pcr-strips',
 'biorad-hardshell-96-PCR',
 'e-gelgol',
 'fixed-trash',
 'hampton-1ml-deep-block',
 'magdeck',
 'opentrons-aluminum-block-2ml-eppendorf',
 'opentrons-aluminum-block-2ml-screwcap',
 'opentrons-aluminum-block-96-PCR-plate',
 'opentrons-aluminum-block-PCR-strips-200ul',
 'opentrons-tiprack-1000ul',
 'opentrons-tiprack-10ul',
 'opentrons-tiprack-300ul',
 'opentrons-tuberack-1.5ml-eppendorf',
 'opentrons-tuberack-15_50ml',
 'opentrons-tuberack-15ml',
 'opentrons-tuberack-2ml-eppendorf',
 'opentrons-tuberack-2ml-screwcap',
 'opentrons-tuberack-50ml',
 'point',
 'rigaku-compact-crystallization-plate',
 'small_vial_rack_16x45',
 'tall-fixed-trash',
 'tempdeck',
 'temperature-plate',
 'tiprack-1000ul',
 'tiprack-10ul',
 'tiprack-10ul-H',
 'tiprack-200ul',
 'trash-box',
 'trough-12row',
 'trough-12row-short',
 'trough-1row-25ml',
 'trough-1row-test',
 'tube-rack-.75ml',
 'tube-rack-15_50ml',
 'tube-rack-2ml',
 'tube-rack-2ml-9x9',
 'tube-rack-5ml-96',
 'tube-rack-80well',
 'wheaton_vial_rack']

In [ ]:
3dp_rack = labware.create(
    '3dp_rack',                    # name of you container
    grid=(4, 6),                    # specify amount of (rows, columns)
    spacing=(12, 12),               # distances (mm) between each (row, column)
    diameter=5,                     # diameter (mm) of each well on the plate
    depth=10,                       # depth (mm) of each well on the plate
    volume=170)

In [ ]:
josh_rack = labware.create(
    'josh_rack',                    # name of you container
    grid=(3, 6),                    # specify amount of (rows, columns)
    spacing=(12, 12),               # distances (mm) between each (row, column)
    diameter=5,                     # diameter (mm) of each well on the plate
    depth=10,                       # depth (mm) of each well on the plate
    volume=170)

# Need info on: 
## tiprack_tipone_10ul (or w/e) other tips they're using now
## qiagen plate? I think we use standard 96ers (10/15/33 for flat/tall/deep)

In [ ]:
tips1 = labware.load('tiprack-10ul', '2')
tips2 = labware.load('tiprack-10ul', '2')
tips3 = labware.load('tiprack-10ul', '2')
tubes1 = labware.load('tube-rack-2ml','5')
plate1 = labware.load('96-PCR-tall', '2')

In [ ]:
pipette = instruments.P10_Single(mount='left',tip_racks=[tips,tips2,tips3])
trash = labware.load('trash-box', '10')
trash2 = labware.load('trash-box', '11')

In [2]:
print(os.getcwd())
df = pd.read_csv(input_file)

c:\users\brian\google drive\roy_brian\brian\ot2

In [9]:
#clean up list. This can change if the thing changes

df_org = df.iloc[4:len(df.index)-3,0:9]
df_org.rename(columns=df_org.iloc[0], inplace=True)
px = df_org.iloc[1:len(df_org.index)]
px["Position"] = px["Row"] + px["Column"].map(str)
px

C:\Users\Brian\AppData\Local\Enthought\Canopy\edm\envs\Pythontest\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Row,Column,Volume of Media,Volume of BY4741 cells,Volume of DBVPG1373 cells,Volume of YPS606,Volume of DMSO,Volume of Terbinafine,Volume of Voriconozole,Position
5,A,1,136.5,7.5,NaN,NaN,3,3,NaN,A1
6,A,2,136.5,7.5,NaN,NaN,4,2,NaN,A2
7,A,3,136.5,7.5,NaN,NaN,5,1,NaN,A3
8,A,4,136.5,7.5,NaN,NaN,6,0,NaN,A4
9,A,5,138.5783133,NaN,5.421686747,NaN,3,3,NaN,A5
10,A,6,138.5783133,NaN,5.421686747,NaN,4,2,NaN,A6
11,A,7,138.5783133,NaN,5.421686747,NaN,5,1,NaN,A7
12,A,8,138.5783133,NaN,5.421686747,NaN,6,0,NaN,A8
13,A,9,141.2574354,NaN,NaN,2.742564603,3,3,NaN,A9
14,A,10,141.2574354,NaN,NaN,2.742564603,4,2,NaN,A10
15,A,11,141.2574354,NaN,NaN,2.742564603,5,1,NaN,A11
16,A,12,141.2574354,NaN,NaN,2.742564603,6,0,NaN,A12
17,B,1,136.5,7.5,NaN,NaN,3,3,NaN,B1
18,B,2,136.5,7.5,NaN,NaN,4,2,NaN,B2
19,B,3,136.5,7.5,NaN,NaN,5,1,NaN,B3
20,B,4,136.5,7.5,NaN,NaN,6,0,NaN,B4
21,B,5,138.5783133,NaN,5.421686747,NaN,3,3,NaN,B5
22,B,6,138.5783133,NaN,5.421686747,NaN,4,2,NaN,B6
23,B,7,138.5783133,NaN,5.421686747,NaN,5,1,NaN,B7
24,B,8,138.5783133,NaN,5.421686747,NaN,6,0,NaN,B8
25,B,9,141.2574354,NaN,NaN,2.742564603,3,3,NaN,B9
26,B,10,141.2574354,NaN,NaN,2.742564603,4,2,NaN,B10
27,B,11,141.2574354,NaN,NaN,2.742564603,5,1,NaN,B11
28,B,12,141.2574354,NaN,NaN,2.742564603,6,0,NaN,B12
29,C,1,134.64375,7.5,NaN,NaN,5.98125,NaN,1.875,C1
30,C,2,132.7875,7.5,NaN,NaN,5.9625,NaN,3.75,C2
31,C,3,127.21776,7.5,NaN,NaN,5.90624,NaN,9.376,C3
32,C,5,136.7220633,NaN,5.421686747,NaN,5.98125,NaN,1.875,C5
33,C,6,134.8658133,NaN,5.421686747,NaN,5.9625,NaN,3.75,C6
34,C,7,129.2960733,NaN,5.421686747,NaN,5.90624,NaN,9.376,C7
...,...,...,...,...,...,...,...,...,...,...
45,D,10,137.5449354,NaN,NaN,2.742564603,5.9625,NaN,3.75,D10
46,D,11,131.9751954,NaN,NaN,2.742564603,5.90624,NaN,9.376,D11
47,E,1,134.64375,7.5,NaN,NaN,4.98125,1,1.875,E1
48,E,2,132.7875,7.5,NaN,NaN,3.9625,2,3.75,E2
49,E,3,127.21776,7.5,NaN,NaN,2.90624,3,9.376,E3
50,E,5,138.5783133,NaN,5.421686747,NaN,5,1,0,E5
51,E,6,134.8658133,NaN,5.421686747,NaN,3.9625,2,3.75,E6
52,E,7,129.2960733,NaN,5.421686747,NaN,2.90624,3,9.376,E7
53,E,9,141.2574354,NaN,NaN,2.742564603,5,1,0,E9
54,E,10,137.5449354,NaN,NaN,2.742564603,3.9625,2,3.75,E10
55,E,11,131.9751954,NaN,NaN,2.742564603,2.90624,3,9.376,E11
56,F,1,127.21776,7.5,NaN,NaN,2.90624,3,9.376,F1
57,F,2,132.7875,7.5,NaN,NaN,3.9625,2,3.75,F2
58,F,3,136.5,7.5,NaN,NaN,5,1,0,F3
59,F,5,129.2960733,NaN,5.421686747,NaN,2.90624,3,9.376,F5
60,F,6,134.8658133,NaN,5.421686747,NaN,3.9625,2,3.75,F6
61,F,7,138.5783133,NaN,5.421686747,NaN,5,1,0,F7
62,F,9,131.9751954,NaN,NaN,2.742564603,2.90624,3,9.376,F9
63,F,10,137.5449354,NaN,NaN,2.742564603,3.9625,2,3.75,F10
64,F,11,141.2574354,NaN,NaN,2.742564603,5,1,0,F11
65,G,1,142.5,7.5,NaN,NaN,0,0,NaN,G1
66,G,2,142.5,7.5,NaN,NaN,0,0,NaN,G2
67,G,5,144.5783133,NaN,5.421686747,NaN,0,0,NaN,G5
68,G,6,144.5783133,NaN,5.421686747,NaN,0,0,NaN,G6
69,G,9,147.2574354,NaN,NaN,2.742564603,0,0,NaN,G9
70,G,10,147.2574354,NaN,NaN,2.742564603,0,0,NaN,G10
71,H,1,146,0,NaN,NaN,3,1,NaN,H1
72,H,2,146,0,NaN,NaN,3,1,NaN,H2
73,H,3,147,0,NaN,NaN,3,NaN,0,H3
74,H,4,147,0,NaN,NaN,3,NaN,0,H4

In [4]:
px.fillna(0, inplace=True)

C:\Users\Brian\AppData\Local\Enthought\Canopy\edm\envs\Pythontest\lib\site-packages\pandas\core\frame.py:2754: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

,Row,Column,Volume of Media,Volume of BY4741 cells,Volume of DBVPG1373 cells,Volume of YPS606,Volume of DMSO,Volume of Terbinafine,Volume of Voriconozole
5,A,1,136.5,7.5,0,0,3,3,0
6,A,2,136.5,7.5,0,0,4,2,0
7,A,3,136.5,7.5,0,0,5,1,0
8,A,4,136.5,7.5,0,0,6,0,0
9,A,5,138.5783133,0,5.421686747,0,3,3,0
10,A,6,138.5783133,0,5.421686747,0,4,2,0
11,A,7,138.5783133,0,5.421686747,0,5,1,0
12,A,8,138.5783133,0,5.421686747,0,6,0,0
13,A,9,141.2574354,0,0,2.742564603,3,3,0
14,A,10,141.2574354,0,0,2.742564603,4,2,0
15,A,11,141.2574354,0,0,2.742564603,5,1,0
16,A,12,141.2574354,0,0,2.742564603,6,0,0
17,B,1,136.5,7.5,0,0,3,3,0
18,B,2,136.5,7.5,0,0,4,2,0
19,B,3,136.5,7.5,0,0,5,1,0
20,B,4,136.5,7.5,0,0,6,0,0
21,B,5,138.5783133,0,5.421686747,0,3,3,0
22,B,6,138.5783133,0,5.421686747,0,4,2,0
23,B,7,138.5783133,0,5.421686747,0,5,1,0
24,B,8,138.5783133,0,5.421686747,0,6,0,0
25,B,9,141.2574354,0,0,2.742564603,3,3,0
26,B,10,141.2574354,0,0,2.742564603,4,2,0
27,B,11,141.2574354,0,0,2.742564603,5,1,0
28,B,12,141.2574354,0,0,2.742564603,6,0,0
29,C,1,134.64375,7.5,0,0,5.98125,0,1.875
30,C,2,132.7875,7.5,0,0,5.9625,0,3.75
31,C,3,127.21776,7.5,0,0,5.90624,0,9.376
32,C,5,136.7220633,0,5.421686747,0,5.98125,0,1.875
33,C,6,134.8658133,0,5.421686747,0,5.9625,0,3.75
34,C,7,129.2960733,0,5.421686747,0,5.90624,0,9.376
...,...,...,...,...,...,...,...,...,...
48,E,2,132.7875,7.5,0,0,3.9625,2,3.75
49,E,3,127.21776,7.5,0,0,2.90624,3,9.376
50,E,5,138.5783133,0,5.421686747,0,5,1,0
51,E,6,134.8658133,0,5.421686747,0,3.9625,2,3.75
52,E,7,129.2960733,0,5.421686747,0,2.90624,3,9.376
53,E,9,141.2574354,0,0,2.742564603,5,1,0
54,E,10,137.5449354,0,0,2.742564603,3.9625,2,3.75
55,E,11,131.9751954,0,0,2.742564603,2.90624,3,9.376
56,F,1,127.21776,7.5,0,0,2.90624,3,9.376
57,F,2,132.7875,7.5,0,0,3.9625,2,3.75
58,F,3,136.5,7.5,0,0,5,1,0
59,F,5,129.2960733,0,5.421686747,0,2.90624,3,9.376
60,F,6,134.8658133,0,5.421686747,0,3.9625,2,3.75
61,F,7,138.5783133,0,5.421686747,0,5,1,0
62,F,9,131.9751954,0,0,2.742564603,2.90624,3,9.376
63,F,10,137.5449354,0,0,2.742564603,3.9625,2,3.75
64,F,11,141.2574354,0,0,2.742564603,5,1,0
65,G,1,142.5,7.5,0,0,0,0,0
66,G,2,142.5,7.5,0,0,0,0,0
67,G,5,144.5783133,0,5.421686747,0,0,0,0
68,G,6,144.5783133,0,5.421686747,0,0,0,0
69,G,9,147.2574354,0,0,2.742564603,0,0,0
70,G,10,147.2574354,0,0,2.742564603,0,0,0
71,H,1,146,0,0,0,3,1,0
72,H,2,146,0,0,0,3,1,0
73,H,3,147,0,0,0,3,0,0
74,H,4,147,0,0,0,3,0,0
75,0,0,0,0,0,0,0,0,0
76,0,0,0,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0

In [ ]:
start_time = time.time()

In [ ]:
#Talk to alex again; try to work out a quicker way of doing things

In [ ]:
#DMSO for columns (A-F)
col_number = 1
for col in used_cols:
    pipette.transfer(
        dmso_vol1,
        tubes1.wells(dmso_loc),
        plate.cols(col),
        blow_out=True,
        new_tip='always'
        touch_tip=True)
    col_number += 1

In [ ]:
#DMSO for rows (1-6)
for row in used_rows2:
        pipette.transfer(
        dmso_vol2,
        tubes1.wells(dmso_loc),
        plate.rows(row),
        blow_out=True,
        new_tip='always'
        touch_tip=True)

In [ ]:
#DMSO for rows (6-12)
for row in used_rows3:
        pipette.transfer(
        dmso_vol3,
        tubes1.wells(dmso_loc),
        plate.rows(row),
        blow_out=True,
        new_tip='always'
        touch_tip=True)

In [ ]:
#Drug for Columns (A-F)
col_number = 1
for col in used_cols:
    pipette.transfer(
        drug_vol1,
        tubes1.wells(drug_stock_loc[col]),
        plate.cols(col),
        blow_out=True,
        new_tip='always'
        touch_tip=True)
    col_number += 1

In [ ]:
#Drug for Rows (1-6)
for row in used_rows2:
        pipette.transfer(
        drug_vol2,
        tubes1.wells(drug_stock_loc[row]),
        plate.rows(row),
        blow_out=True,
        new_tip='always'
        touch_tip=True)

In [ ]:
#Drug for Rows (6-12)
for row in used_rows3:
        pipette.transfer(
        drug_vol3,
        tubes1.wells(drug_stock_loc[row]),
        plate.rows(row),
        blow_out=True,
        new_tip='always'
        touch_tip=True)

In [ ]:
end_time = time.time()
print("Spent"+str(end_time-start_time)+"seconds")